#! /bin/bash

inotifywait -e close_write,moved_to,create -m . |
    while read -r directory events filename; do
	if [ "$filename" = "tictactoe.toc" ]; then
	    rm tic.html
	    ./scripter.toc.out tictactoe.toc > tic.html
	fi
    done
